import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "sign in - up form",
  description: "Generated by Hosein.dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
